format:
    cargo fmt

check:
    cargo fmt --check
    cargo check --all-targets --bins --all-features
    cargo sqlx prepare --check -- --all-targets --all-features
    
test:
    cargo test

prepare:
    cargo sqlx prepare -- --all-targets --all-features