-- this file was generated by claude based on the data in etc/discord-polls.yml
WITH poll_data (grand_prix_key, vote_type, vote_count) AS (
    VALUES
        ('great-britain', 'FullRace', 27),
        ('great-britain', 'RaceIn30', 21),
        ('great-britain', 'Highlights', 3),
        ('austria', 'FullRace', 4),
        ('austria', 'RaceIn30', 31),
        ('austria', 'Highlights', 14),
        ('barcelona-catalunya', 'FullRace', 33),
        ('barcelona-catalunya', 'RaceIn30', 23),
        ('barcelona-catalunya', 'Highlights', 2),
        ('monaco', 'FullRace', 44),
        ('monaco', 'RaceIn30', 10),
        ('monaco', 'Highlights', 6),
        ('miami', 'FullRace', 32),
        ('miami', 'RaceIn30', 18),
        ('miami', 'Highlights', 0),
        ('japan', 'FullRace', 9),
        ('japan', 'RaceIn30', 17),
        ('japan', 'Highlights', 1),
        ('australia', 'FullRace', 38),
        ('australia', 'RaceIn30', 10),
        ('australia', 'Highlights', 1)
),
poll_sessions AS (
    SELECT s.id AS session_id, pd.vote_type, pd.vote_count
    FROM poll_data pd
    JOIN race_weekend rw
        ON rw.year = 2026
        AND rw.grand_prix_id = pd.grand_prix_key
    JOIN session s
        ON s.weekend_id = rw.id
        AND s.session_type = 'race'
)
INSERT INTO votes (vote_type, user_identifier, session_id)
SELECT ps.vote_type::vote_type, gen_random_uuid()::text, ps.session_id
FROM poll_sessions ps
CROSS JOIN LATERAL generate_series(1, ps.vote_count);
